<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'tests\\upvote\\controllers\\commentcontrollertest' => '/Tests/Upvote/Controllers/CommentControllerTest.php',
                'tests\\upvote\\controllers\\mastercontrollertest' => '/Tests/Upvote/Controllers/FrontControllerTest.php',
                'tests\\upvote\\controllers\\mockcommentcontroller' => '/Tests/Upvote/Controllers/CommentControllerTest.php',
                'tests\\upvote\\controllers\\mockcontroller' => '/Tests/Upvote/Controllers/MockController.php',
                'upvote\\controllers\\commentcontroller' => '/Upvote/Controllers/CommentController.php',
                'upvote\\controllers\\frontcontroller' => '/Upvote/Controllers/FrontController.php',
                'upvote\\controllers\\indexcontroller' => '/Upvote/Controllers/IndexController.php',
                'upvote\\controllers\\storycontroller' => '/Upvote/Controllers/StoryController.php',
                'upvote\\controllers\\usercontroller' => '/Upvote/Controllers/UserController.php',
                'upvote\\exceptions\\usernotauthenticatedexception' => '/Upvote/Exceptions/UserNotAuthenticatedException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
